#INCLUDE "Totvs.ch"

/*/{protheus.doc} mta410T
*******************************************************************************************
Ponto de Entrada no termino da gravação do pedido de vendas
 
@author: Marcelo Celi Marques
@since: 15/12/2020
@param: 
@return:
@type function: Usuario
*******************************************************************************************
/*/
User Function mta410T()
u_BoAtuStPv(SC5->C5_NUM)
Return
